config/routes.rb
Omrails::Application.routes.draw do
  resources :collections

  get "users/show"

  resources :pins do

  end

  devise_for :users

  match 'users/:id' => 'users#show', as: :user

  match '/pins/:tag' => 'pins#index', as: 'filter'

  

  get 'photos' => 'collections#index'
  
  match "/pins/:tag" => "pins#index"

  get 'projects' => 'pins#project'

  root :to => 'pins#index'
  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  attr_accessible :description, :collection_name
	validates :collection_name, presence: true

  has_many :pins
  belongs_to :user
  
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  	attr_accessible :description, :image, :image_remote_url, :collection_id, :tag


  	validates :description, presence: true
  	validates :user_id, presence: true
  	has_attached_file :image, styles: { medium: "320x240>"}  #to do a fixed size use get :medium => "320x240>"
	
  	validates_attachment :image, presence: true,
  								content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  								size: { less_than: 10.megabytes }


  	belongs_to :user
  	belongs_to :collection

    def image_remote_url=(url_value)
      self.image = URI.parse(url_value) unless url_value.blank?
      super 
    end
    
    def pin_params
      params.permit(:id, :tag)
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, #:recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

has_many :pins
has_many :collections

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @collections }
    end
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    @collection = Collection.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/new
  # GET /collections/new.json
  def new
    @collection = current_user.collections.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @collection }
    end
  end

  # GET /collections/1/edit
  def edit
    @collection = current_user.collections.find(params[:id])
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = current_user.collections.new(params[:collection])

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: 'Collection was successfully created.' }
        format.json { render json: @collection, status: :created, location: @collection }
      else
        format.html { render action: "new" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /collections/1
  # PUT /collections/1.json
  def update
    @collection = current_user.collections.find(params[:id])

    respond_to do |format|
      if @collection.update_attributes(params[:collection])
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection = current_user.collections.find(params[:id])
    @collection.destroy

    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

 def action

 end

def pin_params
   params.permit(:pin,:description, :image, :tag)
end

def projects
  @pin = Pin.all
end


end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :project]

  # GET /pins
  # GET /pins.json
  def index

    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end


  def project
    @pins = Pin.where(:tag => "project") 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  	@pins = @user.pins.page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/collections/_collection.html.erb
<tr>
        <td><%= collection.collection_name %></td>
        <td><%= link_to 'View', collection %></td>
       
        <% if current_user == collection.user %>
        	<td><%= link_to 'Edit', edit_collection_path(collection) %></td>
        	<td><%= link_to 'Delete', collection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
</tr>

app/views/collections/_form.html.erb
<%= simple_form_for(@collection, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
	<%= f.input :collection_name, as: :text, input_html: {rows: "1"} %>
    <%= f.input :description, as: :text, input_html: {rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>


<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render 'form' %>

<%= link_to 'Show', @collection %> |
<%= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<h4>Photo collections</h4>

<table class = "table">
  <thead>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>

  <tbody>
    <%= render @collections %>
  </tbody>
</table>

<br />

<p>
<%= link_to "Add +", new_collection_path, class: "btn btn-primary btn-small" %>
</p>

app/views/collections/new.html.erb
<h3>New collection</h3>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<div class = "row">
	<div class = "span6 offset0">
		<div class = "well">
			<p>
	  			<%= @collection.collection_name %> by 
	  			<%= @collection.user.name %>

			</p>
<!--			<% if current_user == @collection.user %>
				<%= link_to 'Edit', edit_collection_path(@collection) %> |
			<% end %>
-->


		</div>
	</div>
	
</div>

<div id="pins">
  	<%= render @collection.pins %>

</div>

<!--
<div class = "row"> 
	<%= link_to 'Back', collections_path %> 
</div>
-->

app/views/layouts/_footer.html.erb
<div class= "footer">
		
		<small>
			<%= link_to "Thanks for visiting!","#" %>
			copyright September 2013
		</small>
	
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      
      <%= link_to Date.today, root_path, class: "brand" %> 
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
        <ul class="nav">
			<li> <%= link_to "Home", root_path %></li>
			<li><%= link_to "Photos", photos_path %></li>
      <li><%= link_to "Projects", projects_path %></li>
      	</ul>

		<ul class="nav pull-right">
			<% if user_signed_in? %>
        <li> <%= link_to "Add +", new_pin_path %> </li>
        <li><%= link_to "Add C", new_collection_path %></li>
				<li> <%= link_to "Edit Profile", edit_user_registration_path  %></li>
				<li> <%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
			<% else %>
				<li> <%= link_to "Login", new_user_session_path %></li>
      		<% end %>
      	</ul>

      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	<title>SS Home</title>
	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>

	</head>

	<body>
		<%= render 'layouts/header' %>

 	 <div class="container">
 	 	<% flash.each do |name, msg| %>
            <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
        <% end %>


		<%= yield %>	
		
 
	</div>

		<div class="container">
			<%= render 'layouts/footer' %>
		</div>


	</body>

</html>

app/views/pages/_home.html.erb
<div class="hero-unit">
	<h2>You've found my home page!</h2>
	<p>Find me here on
	<%= link_to "LinkedIn", "http://www.linkedin.com/pub/soniya-sapre/4/87b/362/" %>, 
	<%= link_to "Foursquare", "https://foursquare.com/soni24" %>,  
	<%= link_to "Twitter", "http://twitter.com/soni24" %>,
	<%= link_to "Instagram", "http://instagram.com/soni24" %>, and
	<%= link_to "Flickr", "http://flickr.com/soniya" %>. 
	</p>
	<p>
	<%= link_to "Sign up to post photos!", new_user_registration_path, class: "btn btn-primary btn-small" %>
	</p>
</div>

app/views/pages/about.html.erb
<h1> About </h1>
<p>
	<%= link_to "Twitter", "http://twitter.com" %>
	is a micro blogging service that anyone can use! It's a 
	<%= link_to "public square", "http://en.wikipedia.org/wiki/Public_Square" %>. 
	This is placeholder text
</p>

app/views/pages/home.html.erb
<div class="hero-unit">
	<h1>Welcome to OMR!</h1>
	<p>You've found my home page:
	<%= link_to "Google Search", "http://google.com" %>

	</p>
	<p>
	<%= link_to "Sign up Now!", new_user_registration_path, class: "btn btn-primary btn-small" %>
	</p>
</div>

app/views/pages/photos.html.erb
<%= render 'pages/home' %>

<h4> Photo collections </h4>
<p>
	<%= link_to "Twitter", "http://twitter.com" %>
	is a micro blogging service that anyone can use! It's a 
	<%= link_to "public square", "http://en.wikipedia.org/wiki/Public_Square" %>. 
	This is placeholder text
</p>

app/views/pages/projects.html.erb
<h3> Recent projects </h3>

<h1>Listing projects</h1>
 

<% @pins.each do |pin| %>
  <tr>
    <td><%= pin.description %></td>
  </tr>
<% end %>

 

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  	
  	<%= f.error_notification %>
	<%= f.full_error :image_file_size, class: "alert alert-error" %>
	<%= f.full_error :image_content_type, class: "alert alert-error"%>

  	
   
    <%= f.input :image , label: "Upload an image"%>
    <%= f.input :image_remote_url , label: "or enter a URL"%>

    <%= f.input :description, as: :text, input_html: {rows: "3"} %>

    <%= f.input :collection_id, :collection => Collection.all, :label_method => :collection_name, :prompt => "Select One" %>

    <%= f.input :tag, as: :text, input_html: {rows: "1"} %>  
    
  <div class="form-actions">
    <%= f.button :submit , class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class = "box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
    <p class = "description">
	    <%= pin.description %>
	</p>    

	<p class = "description">
		<strong>
	    Posted by <%= link_to pin.user.name, pin.user %>
		</strong>
	</p>    
   

	<% if current_user == pin.user %>   
		<p> 
	    	<%= link_to 'Edit', edit_pin_path(pin) %>
	    	<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
	<% end %>

</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<% if user_signed_in? %>
<div id="pins">
  <%= render @pins %>

</div>

<div class="container">
<%= will_paginate @pins %>
</div>

<%end%>

app/views/pins/new.html.erb
<h3>New pin</h3>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/project.html.erb
<h4> Recent Projects </h4>


<div id="pins">

  <%= render @pins %>

</div>

app/views/pins/show.html.erb
<div class = "row">
	<div class = "span6 offset3">
		<div class = "well">
		<%= image_tag @pin.image %>


		<p>
  			<%= @pin.description %>
  		</p>
  		<p>
  			<%= @pin.user.name %>
  		</p>
  		<% if current_user == @pin.user %>
  			<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
			<%= link_to 'Back', pins_path %>
		
		</div>
	</div>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<div id = "pins">
	<%= render @pins %>
</div>

<%= will_paginate @pins %>